// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: (() => {
      const url = process.env["DATABASE_URL"];
      if (!url) {
        throw new Error("DATABASE_URL is not set in environment variables");
      }
      // Add SSL parameters for Supabase connections if not already present
      if (
        url.includes("supabase") &&
        !url.includes("sslmode") &&
        !url.includes("ssl=true")
      ) {
        const separator = url.includes("?") ? "&" : "?";
        return `${url}${separator}sslmode=require`;
      }
      return url;
    })(),
  },
});
//npm run reset:processed-activities
